package manager;

import task.Epic;
import task.Subtask;
import task.Task;


import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public abstract class TaskManagerTest<T extends TaskManager> {
    protected T taskManager;

    protected abstract T createTaskManager();

    @BeforeEach
    void setUp() throws IOException {
        taskManager = createTaskManager();
    }

    // Общие тесты для всех реализаций TaskManager
    @Test
    void testTasksAreEqualIfIdEqual() {
        Task t1 = new Task("T", "D", 1, Status.NEW);
        Task t2 = new Task("T2", "D2", 1, Status.DONE);
        assertEquals(t1, t2);
    }

    @Test
    void testSubtaskAndEpicAreEqualIfIdEqual() {
        Epic e1 = new Epic("E", "D", 5, Status.NEW);
        Epic e2 = new Epic("E2", "D2", 5, Status.DONE);
        assertEquals(e1, e2);

        Subtask s1 = new Subtask("S", "D", 10, Status.NEW, 2);
        Subtask s2 = new Subtask("S2", "D2", 10, Status.DONE, 2);
        assertEquals(s1, s2);
    }

    @Test
    void testEpicCannotContainItselfAsSubtask() {
        Epic epic = new Epic("Epic", "Description", 1, Status.NEW);
        Subtask validSubtask = new Subtask("Subtask", "Desc", 2, Status.NEW, epic.getTaskId());
        Subtask invalidSubtask = new Subtask("InvalidSubtask", "Desc", epic.getTaskId(), Status.NEW, epic.getTaskId());

        ArrayList<Subtask> subtasks = new ArrayList<>();
        subtasks.add(validSubtask);
        subtasks.add(invalidSubtask);
        epic.setSubtasks(subtasks);

        for (Subtask sub : epic.getSubtasks()) {
            assertNotEquals(epic.getTaskId(), sub.getTaskId(), "Epic не должен содержать сам себя");
        }
    }

    @Test
    void testSubtaskCannotBeItsOwnEpic() {
        Subtask subtask = new Subtask("S", "D", 42, Status.NEW, 42);
        assertNotEquals(subtask.getTaskId(), subtask.getEpicId(), "Subtask не может ссылаться на себя как на эпик");
    }

    @Test
    void testTaskManagerAddsAndFindsTasksById() {
        Task task = taskManager.addTask(new Task("T", "D"));
        Epic epic = taskManager.addEpic(new Epic("E", "D"));
        Subtask sub = taskManager.addSubtask(new Subtask("S", "D", epic.getTaskId()));

        assertEquals(task, taskManager.getTask(task.getTaskId()));
        assertEquals(epic, taskManager.getEpic(epic.getTaskId()));
        assertEquals(sub, taskManager.getSubtask(sub.getTaskId()));
    }

    @Test
    void testManualAndAutoGeneratedIdsDoNotConflict() {
        Subtask manual = new Subtask("Manual", "D", 99, Status.NEW, 1);
        Epic epic = taskManager.addEpic(new Epic("E", "D"));
        taskManager.addSubtask(manual);

        Subtask auto = taskManager.addSubtask(new Subtask("Auto", "D", epic.getTaskId()));
        assertNotEquals(99, auto.getTaskId(), "Сгенерированный id не должен совпадать с ручным");
    }

    @Test
    void testTaskIsNotChangedByManagerOnAdd() {
        Task original = new Task("T", "D");
        String originalName = original.getTaskName();
        String originalDesc = original.getTaskDescription();
        Status originalStatus = original.getStatus();

        Task added = taskManager.addTask(original);

        assertEquals(originalName, added.getTaskName());
        assertEquals(originalDesc, added.getTaskDescription());
        assertEquals(originalStatus, added.getStatus());
        assertNotEquals(0, added.getTaskId(), "У задачи должен быть присвоен уникальный taskId");
    }

    @Test
    void testManagerAddsTasksToHistoryWhenGetMethodsCalled() {
        Task t = taskManager.addTask(new Task("HistoryTask", "Tracked"));
        Epic e = taskManager.addEpic(new Epic("HistoryEpic", "Tracked"));
        Subtask s = taskManager.addSubtask(new Subtask("HistorySub", "Tracked", e.getTaskId()));

        taskManager.getTask(t.getTaskId());
        taskManager.getEpic(e.getTaskId());
        taskManager.getSubtask(s.getTaskId());

        List<Task> history = taskManager.getHistory();
        assertEquals(3, history.size());
    }

    @Test
    void testLegacyFunctionality() {
        // Проверка сеттеров task.Task
        Task task = new Task("OldName", "OldDesc");
        task.setTaskName("NewName");
        task.setTaskDescription("NewDesc");
        assertEquals("NewName", task.getTaskName());
        assertEquals("NewDesc", task.getTaskDescription());

        // Добавление и обновление task.Task
        Task addedTask = taskManager.addTask(new Task("T1", "D1"));
        addedTask.setTaskName("T1-upd");
        addedTask.setTaskDescription("D1-upd");
        Task updatedTask = taskManager.updateTask(addedTask);
        assertNotNull(updatedTask);
        assertEquals("T1-upd", taskManager.getTask(addedTask.getTaskId()).getTaskName());

        // Проверка deleteTask
        Task toDelete = taskManager.addTask(new Task("ToDel", "D"));
        int delId = toDelete.getTaskId();
        taskManager.deleteTask(delId);
        assertNull(taskManager.getTask(delId));

        // Проверка конструкторов
        Epic epicTmp = taskManager.addEpic(new Epic("Etmp", "DescEtmp"));
        Subtask fullSub = new Subtask("Sfull", "Dfull", 99, Status.NEW, epicTmp.getTaskId());
        assertEquals(99, fullSub.getTaskId());

        Epic fullEpic = new Epic("Efull", "DescEfull", 55, Status.NEW);
        assertEquals(55, fullEpic.getTaskId());

        // Добавление эпика и подзадач
        Epic epic1 = taskManager.addEpic(new Epic("Epic1", "Desc1"));
        Subtask sub1 = taskManager.addSubtask(new Subtask("Sub1", "D1", epic1.getTaskId()));
        Subtask sub2 = taskManager.addSubtask(new Subtask("Sub2", "D2", epic1.getTaskId()));

        // Проверка updateSubtask и статуса эпика
        sub1.setTaskName("Sub1-new");
        sub1.setStatus(Status.DONE);
        taskManager.updateSubtask(sub1);
        assertEquals(Status.IN_PROGRESS, taskManager.getEpic(epic1.getTaskId()).getStatus());

        sub2.setStatus(Status.DONE);
        taskManager.updateSubtask(sub2);
        assertEquals(Status.DONE, taskManager.getEpic(epic1.getTaskId()).getStatus());

        // Проверка clear методов
        taskManager.clearTasks();
        assertTrue(taskManager.getTasks().isEmpty());

        taskManager.clearSubtasks();
        for (Epic e : taskManager.getEpics()) {
            assertTrue(e.getSubtasks().isEmpty());
            assertEquals(Status.NEW, e.getStatus());
        }

        taskManager.clearEpics();
        assertTrue(taskManager.getEpics().isEmpty());
        assertTrue(taskManager.getSubtasks().isEmpty());
    }
}